<?php

/**
 * The uconn banner uses Liquid, so we need to parse and render
 * the banner using the php port of Liquid, php-liquid.
 */
require(dirname(__FILE__) . '/php-liquid/Liquid.class.php');


/**
 * Add the rendered version of the banner css code.
 */
function uconn_banner_preprocess_html(&$variables) {
   drupal_add_css(drupal_get_path('module', 'uconn_banner') . '/banner/_site/banner.css');
}


function uconn_banner_page_build (&$page) {

  $search_block = module_invoke('search', 'block_view', 'search');

  /**
   * Variables that we want to inject into the banner.
   */ 
  $vars = array( 
    'site' => array(
      'name' => variable_get('site_name', false),
      'department' => theme_get_setting('uconn_of_organization'),
      'department_url' => theme_get_setting('uconn_of_organization_url'),
      'search' => render( $search_block )
    )
  );


  if (!path_is_admin(current_path())) {
      
      $liquid = new LiquidTemplate();
      
      $page['page_top']['uconn_banner'] = array(
         '#weight' => 0, 
         '#markup' => $liquid->parse(file_get_contents(dirname(__FILE__) . '/banner/_includes/banner.html'))->render($vars)
      );       
  }

}